environment: localhost
server:
  port: 9090
  servlet:
    context-path: /authsox
spring:
  kafka:
      bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5433/AUTHS_SOX
    username: postgres
    password: postgres-pwd
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl: update
auth:
  tokens:
    issuer: athssox
    jwt-secret: change-me
    access-token-ttl-seconds: 3600
    refresh-token-ttl-seconds: 2592000
bff:
  base-url: http://localhost:8080/bffssox
outbox:
  email-verify:
    poll-delay-ms: 5000
    batch-size: 50
    retry-delay-seconds: 60
    max-retries: 5
