name: Dev Deploy On Push

on:
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/auth-dev-deploy-on-push.yml"
      - ".github/actions/auth-dev-deploy-run/**"
      - "deploy/auth/**"
      - "boot/**"
      - "api-rest/**"
      - "application/**"
      - "domain/**"
      - "infrastructure/**"
      - "pipe/**"
      - "Dockerfile"
      - "pom.xml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    env:
      DEPLOY_VM_PORT: ${{ vars.DEPLOY_VM_PORT }}
      AUTH_JWT_KEY_ID: ${{ vars.AUTH_JWT_KEY_ID }}
      AUTHS_SOX_DOCKER_NETWORK: ${{ vars.AUTHS_SOX_DOCKER_NETWORK }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Execute dev deployment
        uses: ./.github/actions/auth-dev-deploy-run
        with:
          github_environment: dev
        env:
          DEPLOY_VM_PORT: ${{ vars.DEPLOY_VM_PORT }}
          AUTH_JWT_KEY_ID: ${{ vars.AUTH_JWT_KEY_ID }}
          AUTHS_SOX_DOCKER_NETWORK: ${{ vars.AUTHS_SOX_DOCKER_NETWORK }}
          DEPLOY_VM_HOST: ${{ secrets.DEPLOY_VM_HOST }}
          DEPLOY_VM_USER: ${{ secrets.DEPLOY_VM_USER }}
          DEPLOY_VM_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_VM_SSH_PRIVATE_KEY }}
          GHCR_PULL_USERNAME: ${{ secrets.GHCR_PULL_USERNAME }}
          GHCR_PULL_TOKEN: ${{ secrets.GHCR_PULL_TOKEN }}
          MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
          AUTHS_SOX_DB_PASSWORD: ${{ secrets.AUTHS_SOX_DB_PASSWORD }}
          AUTH_JWT_PRIVATE_KEY: ${{ secrets.AUTH_JWT_PRIVATE_KEY }}
          AUTH_JWT_PUBLIC_KEY: ${{ secrets.AUTH_JWT_PUBLIC_KEY }}
          SECURITY_EMAIL_VERIFICATION_HMAC_SECRET: ${{ secrets.SECURITY_EMAIL_VERIFICATION_HMAC_SECRET }}
