name: SonarCloud

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Materialize Maven settings
        uses: ./.github/actions/materialize-maven-settings
        with:
          maven_repository_username: ${{ vars.MAVEN_REPOSITORY_USERNAME }}
          sitionix_infra_read_token: ${{ secrets.SITIONIX_INFRA_READ_TOKEN }}
          github_forge_it_maven_token: ${{ secrets.GITHUB_FORGE_IT_MAVEN_TOKEN }}
          github_app_afesox_maven_token: ${{ secrets.GITHUB_APP_AFESOX_MAVEN_TOKEN }}
          github_forge_security_maven_token: ${{ secrets.GITHUB_FORGE_SECURITY_MAVEN_TOKEN }}
          github_forge_common_maven_token: ${{ secrets.GITHUB_FORGE_COMMON_MAVEN_TOKEN }}
          output_path: .maven-settings.xml

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.BFF_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -s .maven-settings.xml -B verify
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=sitionix-vv
          -Dsonar.projectKey=sitionix_authorisationservice-sox
          -Dsonar.coverage.jacoco.xmlReportPaths=jacoco-report/target/site/jacoco-aggregate/jacoco.xml
          -Dsonar.token=${SONAR_TOKEN}
          -Dsonar.exclusions=**/target/generated-sources/**,**/generated/**,**/build/**,**/*.md,**/*.txt
